
datasources:
    - host: localhost
      port: 3306
      protocol: tcp
      name: test
      username: root
      password: root
    - host: localhost
      port: 3306
      protocol: tcp
      name: test2
      username: root
      password: root